export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userContants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const productConstants = {
  PRODUCT_ADD_REQUEST: "PRODUCT_ADD_REQUEST",
  PRODUCT_ADD_SUCCESS: "PRODUCT_ADD_SUCCESS",
  PRODUCT_ADD_FAILURE: "PRODUCT_ADD_FAILURE",

  PRODUCT_GET_REQUEST: "PRODUCT_GET_REQUEST",
  PRODUCT_GET_SUCCESS: "PRODUCT_GET_SUCCESS",
  PRODUCT_GET_FAILURE: "PRODUCT_GET_FAILURE",
};
